services:
  front:
    container_name: santa-front
    build:
      context: front
      dockerfile: Dockerfile-build
    networks:
      - nginx-redirect
    volumes:
      - front_certs:/etc/nginx/certs
    ports:
      - "6980:443"
    restart: always

  back:
    container_name: santa-back
    networks:
      - nginx-redirect
      - database
    build:
      context: back
      dockerfile: Dockerfile-build
    env_file: .env
    ports:
      - "3001:3001"
    depends_on:
      - database
    restart: always

  database:
    image: postgres:16
    container_name: santa-database
    networks:
      - database
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

volumes:
  front_certs:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "front/nginx/security"
  database:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "database"

networks:
  database:
    driver: bridge
  nginx-redirect:
    driver: bridge
